NOSTPRY: merged both ecr public and private repository modules.
boldlink/terraform-aws-ecr pull request #4
Opened 2022-05-05 09:20 UTC by JohnNMwangi

In this PR I have merged the public and private ECR modules into 1 module through creation of sub-modules and an example for each.

2022-05-05 15:48 UTC, mariomerco submitted a review, later dismissed
Looks good to me!

2022-05-11 13:24 UTC, mariomerco submitted a review, later dismissed
Looks good to me!. There are two things I'll consider:

1. The KMS key for the private cross-region replication is not the same, which makes sense since the key I used is not multi-region. Either way, I don't know if worth taking a look at this so, if the key actually is multi-region, we could give the ability to reuse the same key (if ECR supports this feature, of course)

2. When destroying the Terraform stack, it doesn't delete the repository in the replica region, which could be a bit annoying. I understand the repository in the other region was really created by ECR and its cross-region replication feature, so Terraform doesn't know anything about it. But, maybe we can just let the note in the documentation mentioning that.

2022-05-19 21:19 UTC, patrickmukumbu requested changes

2022-05-19 21:19 UTC, patrickmukumbu commented on examples/complete/main.tf
> +            },
In a previous PR, I was advised to have this line
`"AWS" : "arn:${data.aws_partition.current.partition}:iam::${data.aws_caller_identity.current.account_id}"`
being
`"AWS" : "arn:${local.partition}:iam::${local.account_id}"`
and the locals being
locals {
partition = data.aws_partition.current.partition
account_id = data.aws_caller_identity.current.account_id
}

2022-05-22 21:47 UTC, hugoalmeida264 requested changes
See my comments.

Question, should we add a module for `aws_ecr_pull_through_cache_rule` here (Add it to the unreleased) or make it a separate module? It is still a repo but syncs from another repo.

2022-05-22 21:47 UTC, hugoalmeida264 commented on PULL_REQUEST_TEMPLATE.md
> +    * [ ] Terraform resources examples build/destroy successfully with Terraform 0.13.7 minimum?
Update the template, it is still pointing to 0.13.7

2022-05-22 21:47 UTC, hugoalmeida264 commented on examples/complete/main.tf
> +  partition  = data.aws_partition.current.partition
Locals should be on `locals.tf`

2022-05-22 21:47 UTC, hugoalmeida264 commented on examples/complete/main.tf
> +  for_each                  = toset(local.name)
Why is the name on a list? A string should be enough.

2022-05-22 21:47 UTC, hugoalmeida264 commented on examples/complete/main.tf
>  }
I would like to see json code inside `jsonencode({})` over herodoc

2022-05-22 21:47 UTC, hugoalmeida264 commented on examples/complete/main.tf
> +  account_id = data.aws_caller_identity.current.account_id
The untagged rule should be 1 day, by and large, you don't want untagged images, if they are there mist often than not it was by mistake or error and should be cleaned as soon as possible.

2022-05-22 21:47 UTC, hugoalmeida264 commented on examples/complete/main.tf
> +  account_id = data.aws_caller_identity.current.account_id
This is going to sound weird but `30` images to keep make more sense ;)

2022-05-22 21:47 UTC, hugoalmeida264 commented on examples/complete/main.tf
>          {
Use `jsonencode({})`

2022-05-22 21:47 UTC, hugoalmeida264 commented on main.tf
> +  scan_on_push              = var.scan_on_push
Should we remove this option since it is going to be deprecated?

2022-05-22 21:47 UTC, hugoalmeida264 commented on main.tf
> +  environment               = var.environment
We should only have one tag and not mandatory ones

2022-05-22 21:47 UTC, hugoalmeida264 commented on modules/private/main.tf
> +    scan_on_push = var.scan_on_push
Should we leave this here.

2022-05-22 21:47 UTC, hugoalmeida264 commented on modules/private/main.tf
> +  dynamic "encryption_configuration" {
Encryption should be enabled by default using at a min the `AWS Owned KMS key`

2022-05-23 16:43 UTC, ndegwajohn commented
> See my comments.
> 
> Question, should we add a module for `aws_ecr_pull_through_cache_rule` here (Add it to the unreleased) or make it a separate module? It is still a repo but syncs from another repo.

I think it would be best to have it as part of the module that will have the other global settings, such as registry policies.

2022-05-23 20:25 UTC, hugoalmeida264 submitted a review, later dismissed

2022-05-24 07:31 UTC, patrickmukumbu approved these changes

2022-05-24 07:39 UTC, merged